### ISSUE TITLE
deploy script fails getting iotHubServiceConnectionString

### ISSUE THREAD

**Issue by darax** [Microsoft/SmartHotel360-IoT#44]
I suspect the outputs of az iot hub show-connection-string have changed.  The current script looks like 
$iotHubServiceConnectionString = ((az iot hub show-connection-string -n $iotHubName --resource-group $resourceGroupName --policy-name service) | ConvertFrom-Json).cs

and I believe it should be 
$iotHubServiceConnectionString = ((az iot hub show-connection-string -n $iotHubName --resource-group $resourceGroupName --policy-name service) | ConvertFrom-Json).**connectionString**

https://github.com/Azure/azure-iot-cli-extension/blob/dev/HISTORY.rst

**Comment by dasanagu** [comment]
Thank you @darax we have created a [PR](https://github.com/Microsoft/SmartHotel360-IoT/pull/45) with this fix.
