### ISSUE TITLE
Error occurred during Digital Twins provisioning: System.Exception: Http request failed

### ISSUE THREAD

**Issue by shmisra** [microsoft/SmartHotel360-IoT#46]
A customer is getting error as shown below while doing setup for SmartHotel 360

Error occurred during Digital Twins provisioning: System.Exception: Http request failed: {'error':{'code':'403.600.000.0 01','message':'System error.'}}

at SmartHotelJoT.Provisioning.Common.RestHelper.GetIdAsync(HttpResponseMessage response)
at SmartHotel.IoT.Provisioning.Program.CreateSpaceAsync(HttpClient httpClient, Space space)

at SmartHotel.IoT.Provisioning.Program.CreateSpaceAsync(HttpClient httpClient, SpaceDescription spaceDescription, Gui d parentld, Guid keystoreld, UserAadObjectIdsDescription userAadObjectIds)

at SmartHotel.IoT.Provisioning.Program.CreateSpacesAsync(HttpClient httpClient, IList`1 spaceDescriptions, Guid paren tld, Guid keystoreld, UserAadObjectIdsDescription userAadObjectIds)

at SmartHotel.IoT.Provisioning.Program.OnExecuteAsync()

E:\\I0T2\\Source\\ARM\\deploy.ps1 : An error occurred while provisioning Azure Digital Twins.

The "Http request failed: {'error':{'code':'403.600.000.0 01','message':'System error.'}}" appears that Response Status is : 403
Does that mean: The user which is trying this provision is not the same user that deployed the DT instance. If you are getting 403, it means you are not authorized by the system and you need higher permissions.

Should the resolution be similar to https://github.com/MicrosoftDocs/azure-docs/issues/27503 ?

**Comment by willyt150** [comment]
That would appear to be the same issue and yes the resolution should be similar.

**Comment by shmisra** [comment]
The issue 27503 does not help to resolve the situation. 
Failure in deployment of Smart Hotel 360 IOT application. 
Getting error:

Deployment failed. Correlation ID: 3635424f-911f-48ca-a662-d993213d52f0. {
"error": {
"code": "InternalServerError",
"message": "There was an unexpected InternalServerError. Please try again later. x-ms-correlation-request-id: b3fd598c-614e-4ed2-9aba-b948065dee0c"
}
}
E:\SmartHotel360-IoT\Source\ARM\deploy.ps1 : You cannot call a method on a null-valued expression.
At line:1 char:1
+ .\deploy.ps1 -subscriptionId 5851fa5b-5ccd-4762-85cf-35bfc37bc104 -cl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (:) [deploy.ps1], RuntimeException
+ FullyQualifiedErrorId : InvokeMethodOnNull,deploy.ps1

Deleted the Digital Twin instance but it still fails. 
Interesting, the below command always fails. Doesn't look like this is a valid command to 
obtain the service principal Id.

Get-AzureRmADServicePrincipal -ApplicationId {app Id}

 - Please guide on the latest steps to deploy Smart Hotel 360 IoT application.
