### ISSUE TITLE
Error deploying: failed creating Digital Twins

### ISSUE THREAD

**Issue by munip** [microsoft/SmartHotel360-IoT#48]
While running the deploy.ps1, the deployment stops failing on creating Digital Twins with the following error in the error log:

Operation Name : Create Microsoft.IoTSpaces Graph
 
 
Cannot provision more instances in 'WestUS2'. Please try a different location.

I tried all locations with Digital Twins, but got the same error.

**Comment by willyt150** [comment]
Do you already have a Digital Twins instance in your subscription?

There's a limitation currently of 1 instance per subscription

https://docs.microsoft.com/en-us/azure/digital-twins/concepts-service-limits

**Comment by BallermoreBro** [comment]
I am getting a similar error when i look up in the activity log it seems to complain about scale operations for my region or subscription

Azure Error: InvalidTemplateDeployment
Message: The template deployment 'SmartHotel360-IoT-Demo' is not valid according to the validation procedure. The tracking id is 'fc44d133-8256-4af4-a715-ef0c5efff23d'. See inner errors for details.
Exception Details:
        Error Code: ValidationForResourceFailed
        Message: Validation failed for a resource. Check 'Error.Details[0]' for more information.
C:\Users\593347\Documents\General BAH\FY20 Innovator Project\SmartHotel360-IoT-master\Source\ARM\deploy.ps1 : You
cannot call a method on a null-valued expression.
